package com.bw.movie.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.bw.movie.bean.ComingSoonResultBean;

import com.bw.movie.dao.ComingSoonResultBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig comingSoonResultBeanDaoConfig;

    private final ComingSoonResultBeanDao comingSoonResultBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        comingSoonResultBeanDaoConfig = daoConfigMap.get(ComingSoonResultBeanDao.class).clone();
        comingSoonResultBeanDaoConfig.initIdentityScope(type);

        comingSoonResultBeanDao = new ComingSoonResultBeanDao(comingSoonResultBeanDaoConfig, this);

        registerDao(ComingSoonResultBean.class, comingSoonResultBeanDao);
    }
    
    public void clear() {
        comingSoonResultBeanDaoConfig.clearIdentityScope();
    }

    public ComingSoonResultBeanDao getComingSoonResultBeanDao() {
        return comingSoonResultBeanDao;
    }

}
